version: '3.1'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    ports:
      - 8080:8080
    volumes:
      - .:/home/app

  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: url_shortner
      MYSQL_ROOT_PASSWORD: passphrase
    volumes:
      - sql_data:/var/lib/mysql

volumes:
  sql_data: